### ISSUE TITLE
reads fastq error

### ISSUE THREAD

**Issue by xwhld** [ParkinsonLab/MetaPro#16]
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.

**Comment by billytaj** [comment]
Hi,
please elaborate on your particular issue. I'm having trouble understanding your specific problem.

**Comment by susheelbhanu** [comment]
I have a similar issue. 

The stdout for the error is as follows:
```bash
2026-02-13 17:51:03.238054 continuing from: vector_filter
2026-02-13 17:51:03.238583 running: rRNA_filter
2026-02-13 17:51:03.239215 running: rRNA_filter_split_pair_2
2026-02-13 17:51:03.239233 splitting: pair_2  for rRNA filtration
2026-02-13 17:51:03.258317 running: rRNA_filter_split_pair_1
2026-02-13 17:51:03.258348 splitting: pair_1  for rRNA filtration
2026-02-13 17:51:03.261471 running: rRNA_filter_split_singletons
2026-02-13 17:51:03.261502 splitting: singletons  for rRNA filtration
2026-02-13 17:51:03.264388 closing down processes:  3
2026-02-13 17:51:03.264441 closed down: 0/3            ^M2026-02-13 17:51:03.709301 closed down: 1/3            ^M2026-02-13 17:51:03.711767 closed down: 2/3            ^M2026-02-13 17:51:05.716360 /ei/.project-scratch/5/542de014-1e71-4955-945a-5d2ab09567a7/CEHsoil/sushee
l/metapro_runs/r258/rRNA_filter/rRNA_filter_prep.txt exists: adding to it
2026-02-13 17:51:05.726093 /ei/.project-scratch/5/542de014-1e71-4955-945a-5d2ab09567a7/CEHsoil/susheel/metapro_runs/r258/rRNA_filter/data/jobs/rRNA_filter_prep_pair_2 not found.  kill the pipe.  restart this stage
```

it's associated error
```bash
splitting fastq for pair_2
splitting fastq for singletons
splitting fastq for pair_1
Traceback (most recent call last):
  File "/pipeline/Scripts/read_split.py", line 116, in <module>
    split_fastq(input_file, output_name, split_count)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pipeline/Scripts/read_split.py", line 23, in split_fastq
    fastq_df = pd.read_csv(file_name_in, header=None, names=[None], sep="\n", skip_blank_lines = False, quoting=3)
  File "/usr/local/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1013, in read_csv
    kwds_defaults = _refine_defaults_read(
        dialect,
    ...<7 lines>...
        dtype_backend=dtype_backend,
    )
  File "/usr/local/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 2226, in _refine_defaults_read
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
Traceback (most recent call last):
  File "/pipeline/Scripts/read_split.py", line 116, in <module>
    split_fastq(input_file, output_name, split_count)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pipeline/Scripts/read_split.py", line 23, in split_fastq
    fastq_df = pd.read_csv(file_name_in, header=None, names=[None], sep="\n", skip_blank_lines = False, quoting=3)
  File "/usr/local/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1013, in read_csv
    kwds_defaults = _refine_defaults_read(
        dialect,
    ...<7 lines>...
        dtype_backend=dtype_backend,
    )
  File "/usr/local/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 2226, in _refine_defaults_read
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
Traceback (most recent call last):
  File "/pipeline/Scripts/read_split.py", line 116, in <module>
    split_fastq(input_file, output_name, split_count)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pipeline/Scripts/read_split.py", line 23, in split_fastq
    fastq_df = pd.read_csv(file_name_in, header=None, names=[None], sep="\n", skip_blank_lines = False, quoting=3)
  File "/usr/local/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1013, in read_csv
    kwds_defaults = _refine_defaults_read(
        dialect,
    ...<7 lines>...
        dtype_backend=dtype_backend,
    )
  File "/usr/local/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 2226, in _refine_defaults_read
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
not all jobs completed
```
