### ISSUE TITLE
BLAT error

### ISSUE THREAD

**Issue by irvinng98** [ParkinsonLab/MetaPro#35]
Hello,

I'm running into an issue during GA_BWA_merge (that's the last item on bypass_log.txt).

This is the error:
```
2024-11-20 05:15:32.337389 BLAT_pair_2_9028_2005359.fasta job submitted.  mem: 5 GB
2024-11-20 05:15:32.337760 RUNNING: pair_2_9028_blat_838.fasta
2024-11-20 05:15:32.340219 BLAT_pair_2_9028_838.fasta job submitted.  mem: 10 GB
2024-11-20 05:15:32.340568 RUNNING: pair_2_9028_blat_44013.fasta
2024-11-20 05:15:32.342904 BLAT_pair_2_9028_44013.fasta job submitted.  mem: 15 GB
2024-11-20 05:15:32.343233 RUNNING: pair_2_9028_blat_1678.fasta
2024-11-20 05:15:21.107950 BLAT annotation for pair_2_9028 2005359.fasta
2024-11-20 05:15:32.347735 BLAT_pair_2_9028_1678.fasta job submitted.  mem: 20 GB
2024-11-20 05:15:32.348076 RUNNING: pair_2_9028_blat_104264.fasta
2024-11-20 05:15:32.338130 BLAT annotation for pair_2_9028 838.fasta
2024-11-20 05:15:32.350973 BLAT_pair_2_9028_104264.fasta job submitted.  mem: 25 GB
2024-11-20 05:15:32.351303 RUNNING: pair_2_9028_blat_1485.fasta
2024-11-20 05:15:32.340800 BLAT annotation for pair_2_9028 44013.fasta
2024-11-20 05:15:32.355435 BLAT_pair_2_9028_1485.fasta job submitted.  mem: 30 GB
2024-11-20 05:15:32.355782 RUNNING: pair_2_9028_blat_239934.fasta
2024-11-20 05:15:32.343481 BLAT annotation for pair_2_9028 1678.fasta
2024-11-20 05:15:32.359195 BLAT_pair_2_9028_239934.fasta job submitted.  mem: 35 GB
2024-11-20 05:15:32.359543 RUNNING: pair_2_9028_blat_946234.fasta
2024-11-20 05:15:32.348299 BLAT annotation for pair_2_9028 104264.fasta
2024-11-20 05:15:32.362491 BLAT_pair_2_9028_946234.fasta job submitted.  mem: 40 GB
2024-11-20 05:15:32.363208 RUNNING: singletons_990040_blat_816.fasta
2024-11-20 05:15:32.351533 BLAT annotation for pair_2_9028 1485.fasta
2024-11-20 05:15:32.366735 BLAT_singletons_990040_816.fasta job submitted.  mem: 45 GB
2024-11-20 05:15:32.367063 RUNNING: singletons_990040_blat_836.fasta
2024-11-20 05:15:32.356008 BLAT annotation for pair_2_9028 239934.fasta
2024-11-20 05:15:32.370525 BLAT_singletons_990040_836.fasta job submitted.  mem: 50 GB
2024-11-20 05:15:32.370868 RUNNING: singletons_990040_blat_1918540.fasta
2024-11-20 05:15:32.359762 BLAT annotation for pair_2_9028 946234.fasta
2024-11-20 05:15:32.374202 BLAT_singletons_990040_1918540.fasta job submitted.  mem: 55 GB
2024-11-20 05:15:32.374543 RUNNING: singletons_990040_blat_2767887.fasta
2024-11-20 05:15:32.363463 BLAT annotation for singletons_990040 816.fasta
2024-11-20 05:15:32.376884 BLAT_singletons_990040_2767887.fasta job submitted.  mem: 60 GB
2024-11-20 05:15:32.377222 RUNNING: singletons_990040_blat_2518495.fasta
2024-11-20 05:15:32.367345 BLAT annotation for singletons_990040 836.fasta
2024-11-20 05:15:32.380667 BLAT_singletons_990040_2518495.fasta job submitted.  mem: 65 GB
2024-11-20 05:15:32.380987 RUNNING: singletons_990040_blat_375288.fasta
2024-11-20 05:15:32.371141 BLAT annotation for singletons_990040 1918540.fasta
2024-11-20 05:15:32.384018 BLAT_singletons_990040_375288.fasta job submitted.  mem: 70 GB
2024-11-20 05:15:32.384330 RUNNING: singletons_990040_blat_307628.fasta
2024-11-20 05:15:32.374867 BLAT annotation for singletons_990040 2767887.fasta
2024-11-20 05:15:32.388603 BLAT_singletons_990040_307628.fasta job submitted.  mem: 75 GB
2024-11-20 05:15:32.388952 RUNNING: singletons_990040_blat_191303.fasta
2024-11-20 05:15:32.391548 BLAT_singletons_990040_191303.fasta job submitted.  mem: 80 GB
2024-11-20 05:15:32.391878 RUNNING: singletons_990040_blat_572511.fasta
2024-11-20 05:15:32.381297 BLAT annotation for singletons_990040 375288.fasta
2024-11-20 05:15:32.377519 BLAT annotation for singletons_990040 2518495.fasta
2024-11-20 05:15:32.396013 BLAT_singletons_990040_572511.fasta job submitted.  mem: 85 GB
2024-11-20 05:15:32.396347 RUNNING: singletons_990040_blat_1729679.fasta
2024-11-20 05:15:32.384677 BLAT annotation for singletons_990040 307628.fasta
2024-11-20 05:15:32.398866 BLAT_singletons_990040_1729679.fasta job submitted.  mem: 90 GB
2024-11-20 05:15:32.399215 RUNNING: singletons_990040_blat_2005359.fasta
2024-11-20 05:15:32.389246 BLAT annotation for singletons_990040 191303.fasta
2024-11-20 05:15:32.401636 BLAT_singletons_990040_2005359.fasta job submitted.  mem: 95 GB
2024-11-20 05:15:32.401976 RUNNING: singletons_990040_blat_838.fasta
2024-11-20 05:15:32.392161 BLAT annotation for singletons_990040 572511.fasta
2024-11-20 05:15:32.404978 BLAT_singletons_990040_838.fasta job submitted.  mem: 100 GB
2024-11-20 05:15:32.405312 RUNNING: singletons_990040_blat_44013.fasta
2024-11-20 05:15:32.396635 BLAT annotation for singletons_990040 1729679.fasta
2024-11-20 05:15:32.408345 BLAT_singletons_990040_44013.fasta job submitted.  mem: 105 GB
2024-11-20 05:15:32.408672 RUNNING: singletons_990040_blat_1678.fasta
2024-11-20 05:15:32.399495 BLAT annotation for singletons_990040 2005359.fasta
2024-11-20 05:15:32.411748 BLAT_singletons_990040_1678.fasta job submitted.  mem: 110 GB
2024-11-20 05:15:32.412065 RUNNING: singletons_990040_blat_104264.fasta
2024-11-20 05:15:32.402255 BLAT annotation for singletons_990040 838.fasta
2024-11-20 05:15:32.415611 BLAT_singletons_990040_104264.fasta job submitted.  mem: 115 GB
2024-11-20 05:15:32.415943 RUNNING: singletons_990040_blat_1485.fasta
2024-11-20 05:15:32.405607 BLAT annotation for singletons_990040 44013.fasta
2024-11-20 05:15:32.418544 BLAT_singletons_990040_1485.fasta job submitted.  mem: 120 GB
2024-11-20 05:15:32.418864 RUNNING: singletons_990040_blat_239934.fasta
2024-11-20 05:15:32.408968 BLAT annotation for singletons_990040 1678.fasta
2024-11-20 05:15:32.422364 BLAT_singletons_990040_239934.fasta job submitted.  mem: 125 GB
2024-11-20 05:15:32.422688 RUNNING: singletons_990040_blat_946234.fasta
2024-11-20 05:15:32.412362 BLAT annotation for singletons_990040 104264.fasta
2024-11-20 05:15:32.426188 BLAT_singletons_990040_946234.fasta job submitted.  mem: 130 GB
2024-11-20 05:15:32.426890 RUNNING: singletons_9876_blat_816.fasta
2024-11-20 05:15:32.416283 BLAT annotation for singletons_990040 1485.fasta
2024-11-20 05:15:32.430491 BLAT_singletons_9876_816.fasta job submitted.  mem: 135 GB
2024-11-20 05:15:32.430829 RUNNING: singletons_9876_blat_836.fasta
2024-11-20 05:15:32.419203 BLAT annotation for singletons_990040 239934.fasta
2024-11-20 05:15:32.433765 BLAT_singletons_9876_836.fasta job submitted.  mem: 140 GB
2024-11-20 05:15:32.434099 RUNNING: singletons_9876_blat_1918540.fasta
2024-11-20 05:15:32.422988 BLAT annotation for singletons_990040 946234.fasta
2024-11-20 05:15:32.437772 BLAT_singletons_9876_1918540.fasta job submitted.  mem: 145 GB
2024-11-20 05:15:32.438105 RUNNING: singletons_9876_blat_2767887.fasta
2024-11-20 05:15:32.427129 BLAT annotation for singletons_9876 816.fasta
2024-11-20 05:15:32.441713 BLAT_singletons_9876_2767887.fasta job submitted.  mem: 150 GB
2024-11-20 05:15:32.442044 RUNNING: singletons_9876_blat_2518495.fasta
2024-11-20 05:15:32.431129 BLAT annotation for singletons_9876 836.fasta
2024-11-20 05:15:32.445758 BLAT_singletons_9876_2518495.fasta job submitted.  mem: 155 GB
2024-11-20 05:15:32.446096 RUNNING: singletons_9876_blat_375288.fasta
2024-11-20 05:15:32.434370 BLAT annotation for singletons_9876 1918540.fasta
2024-11-20 05:15:32.438394 BLAT annotation for singletons_9876 2767887.fasta
2024-11-20 05:15:32.442344 BLAT annotation for singletons_9876 2518495.fasta
2024-11-20 05:15:32.446393 BLAT annotation for singletons_9876 375288.fasta
Invalid fasta format: sequence size == 0 for element 1796646__A0A1B1S688__A4V02_00140|k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Muribaculaceae.g__Muribaculum.s__
Invalid fasta format: sequence size == 0 for element 1796646__A0A1B1S688__A4V02_00140|k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Muribaculaceae.g__Muribaculum.s__
```

I took a look online and some mentioned this:

> Looks like your input file has variants/SNP's listed for specific positions? This file is NOT going to work with blat (which requires a simple fasta format file at a minimum)

I am using the pre-built databases from your website.

Thanks!

**Comment by irvinng98** [comment]
Hello @billytaj , are you able to provide some insight as to what's potentially going wrong?

**Comment by billylaw8** [comment]
the error is saying there's something off with the fasta file that BLAT got for that run.
Try running BLAT by itself with that specific section for more insight.

The scripts should be produced as one of the interim files.

**Comment by irvinng98** [comment]
Hi @billytaj ,

Thanks for the response. I went back and took a look at what was happening and to be honest, I'm quite confused. I'll use contig_1 as an example.

1) The std output is as follows:
```
2025-01-20 23:00:13.342872 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:13.350075 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:13.359128 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:13.367455 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:13.374933 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:13.382216 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:13.391667 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:13.399624 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
Invalid fasta format: sequence size == 0 for element 1796646__A0A1B1S688__A4V02_00140|k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Muribaculaceae.g__Muribaculum.s__
Invalid fasta format: sequence size == 0 for element 1796646__A0A1B1S688__A4V02_00140|k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Muribaculaceae.g__Muribaculum.s__
2025-01-20 23:00:13.406516 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:39.763462 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:39.772087 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:39.779577 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:39.786458 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:39.792576 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:39.798724 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
2025-01-20 23:00:39.804729 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
not all jobs completed
```

2) Going into the BLAT folder, I see all the files that correspond to contig_1 (eg., BLAT_contigs_1_816.fasta.sh) have only the following line:
```
>&2 echo 2025-01-20 23:00:13.342872 Not running BLAT command on empty file: /ProjectDir/Metapro/output/GA_BWA/final_results/contigs_1.fasta
```
This makes me suspect that something went wrong with BWA

3) In the GA_BWA folder, I see BWA_contigs_1_819.sh. When I run the following bwa command from the script, everything works fine:
```
>&2 echo 2025-01-20 16:43:58.476967 BWA on contigs_1 | /pipeline_tools/BWA/bwa mem -t 80 /ProjectDir/Metapro/output/GA_pre_scan/final_results/816.fasta /ProjectDir/Metapro/output/GA_split/final_results/contigs/contigs_1.fasta | /pipeline_tools/samtools/samtools view > /ProjectDir/Metapro/output/GA_BWA/data/1_bwa/contigs_1_816.sam
```
HOWEVER, the last part of this: "&& touch /ProjectDir/Metapro/output/GA_BWA/data/jobs/contigs_1_816_bwa" I can't do because for some reason, the directory GA_BWA/data/jobs is missing after the run ends and I'm not sure how to get it back.

4) Looking at the final_results folder of GA_BWA, I see files for both contig_1. Here, I compared contig_0.fasta which has content vs contig_1.fasta which doesn't have content. For both, the fasta file of 34098 and 1918540 seem to have issues as they're empty (eg. contigs_0_34098_gene_map.tsv and contigs_0_mapped_genes.fna) but the difference is that contig_1 is empty for some reason. I'm not sure which script is being run to generate contig_1.fasta.

At this point, I'm stuck at what to do as I'm not sure which script to run to fix this issue.

Thanks for your guidance.

**Comment by umerijaz** [comment]
Hi, I am not sure why I am running into this error (sorry for hijacking this thread, I can't seem to create new issues):

MetaPro operating in auto-mode
Forward Reads: /shared5/Simon/emily_beef_trial/Data/MetaT/sequences/105/Raw/105_1_1.fastq
Reverse Reads: /shared5/Simon/emily_beef_trial/Data/MetaT/sequences/105/Raw/105_1_2.fastq
Output filepath: /shared5/Simon/emily_beef_trial/Data/MetaT/processed/105
job path: 105/quality_filter
Traceback (most recent call last):
  File "/pipeline/MetaPro.py", line 250, in <module>
    main(config_file, pair_1, pair_2, single, contig, output_folder, args_pack, tutorial_mode)
  File "/pipeline/MetaPro.py", line 51, in main
    metapro_stage_obj.mp_quality_filter()
  File "/pipeline/MetaPro_stages.py", line 394, in mp_quality_filter
    self.cleanup_quality_start, self.cleanup_quality_end = self.mp_util.launch_stage_simple(self.quality_filter_label, self.quality_path, self.commands, command_list, self.keep_all, self.keep_quality)
  File "/pipeline/MetaPro_utilities.py", line 426, in launch_stage_simple
    if self.check_bypass_log(self.output_folder_path, job_label):
  File "/pipeline/MetaPro_utilities.py", line 132, in check_bypass_log
    open(bypass_log_path, "a").close()
FileNotFoundError: [Errno 2] No such file or directory: '105/order_bypass_log_1.txt'

My configuration file is as follows:

[Databases]
database_path: /software/metaPRO/metaPROdb
UniVec_Core: %(database_path)s/univec_core/UniVec_Core.fasta
Adapter: %(database_path)s/Trimmomatic_adapters/TruSeq3-PE-2.fa
Host: %(database_path)s/human_genome/human_genome.fasta
Rfam: %(database_path)s/Rfam/Rfam.cm
DNA_DB: %(database_path)s/choco_mpro_3/family_group
#DNA_DB: %(database_path)s/chocophlan_h3_chunks
#DNA_DB: /home/billy/choco_h3/choco_h3_group
#DNA_DB_Split: %(database_path)s/ChocoPhlAn/ChocoPhlAn_split/
Prot_DB: %(database_path)s/nr/nr
Prot_DB_reads: %(database_path)s/nr/nr
accession2taxid: %(database_path)s/accession2taxid/accession2taxid
nodes: %(database_path)s/WEVOTE_db/nodes_wevote.dmp
names: %(database_path)s/WEVOTE_db/names_wevote.dmp
Kaiju_db: %(database_path)s/kaiju_db/kaiju_db_nr.fmi
Centrifuge_db: %(database_path)s/centrifuge_db/nt
SWISS_PROT: %(database_path)s/swiss_prot_db/swiss_prot_db
SWISS_PROT_map: %(database_path)s/swiss_prot_db/SwissProt_EC_Mapping.tsv
PriamDB: %(database_path)s/PRIAM_db/
DetectDB: %(database_path)s/DETECTv2
WEVOTEDB: %(database_path)s/WEVOTE_db/
EC_pathway: %(database_path)s/EC_pathway/EC_pathway.txt
path_to_superpath: %(database_path)s/path_to_superpath/pathway_to_superpathway.csv
MetaGeneMark_model: /pipeline_tools/mgm/MetaGeneMark_v1.mod
taxid_tree: %(database_path)s/taxid_trees/class_tree.tsv
kraken2_db: %(database_path)s/kraken2
#[code]
#ga_pre_scan_get_libs = /home/billy/human_flu/30785/ga_pre_scan_get_libs.py


[Tools]
Python = python3
Java = java -jar
cdhit_dup = /pipeline_tools/cdhit_dup/cd-hit-dup
Timmomatic = /pipeline_tools/Trimmomatic/trimmomatic-0.36.jar
AdapterRemoval = /pipeline_tools/adapterremoval/AdapterRemoval
vsearch = /pipeline_tools/vsearch/vsearch
Flash = /pipeline_tools/FLASH/flash
BWA = /pipeline_tools/BWA/bwa
SAMTOOLS = /pipeline_tools/samtools/samtools
BLAT = /pipeline_tools/PBLAT/pblat
DIAMOND = /pipeline_tools/DIAMOND/diamond
Blastp = /pipeline_tools/BLAST_p/blastp
Barrnap = /pipeline_tools/Barrnap/bin/barrnap
#note: needle is quite slow.  This argument can be swapped for stretcher, but stretcher is not as accurate
Needle = /pipeline_tools/EMBOSS-6.6.0/emboss/needle
Blastdbcmd = /pipeline_tools/BLAST_p/blastdbcmd
Makeblastdb = /pipeline_tools/BLAST_p/makeblastdb
Infernal = /pipeline_tools/infernal/cmscan
Kaiju = /pipeline_tools/kaiju/kaiju
Centrifuge = /pipeline_tools/centrifuge/centrifuge
Priam = /pipeline_tools/PRIAM_search/PRIAM_search.jar
Detect = /pipeline/Scripts/Detect_2.2.9.py
BLAST_dir = /pipeline_tools/BLAST_p
WEVOTE = /pipeline_tools/WEVOTE/WEVOTE
Spades = /pipeline_tools/SPAdes/bin/spades.py
MetaGeneMark = /pipeline_tools/mgm/gmhmmp

#default is 30, to coincide with cdhit_dup's default.  
[Settings]
AdapterRemoval_minlength = 30
bypass_log_name = order_bypass_log_1.txt
#debug_stop_flag = order_ta_1
taxa_existence_cutoff = 1
DNA_DB_mode = chocophlan
num_threads = 4


Show_unclassified = No
RPKM_cutoff = 0.01
BWA_cigar_cutoff = 90
BLAT_identity_cutoff = 85
BLAT_length_cutoff = 0.65
BLAT_score_cutoff = 60
DIAMOND_identity_cutoff = 85
DIAMOND_length_cutoff = 0.65
DIAMOND_score_cutoff = 60

#determines how much memory should be free for use with each tool.  [1-99]
BWA_mem_threshold = 2
BLAT_mem_threshold = 2
DIAMOND_mem_threshold = 2
BWA_pp_mem_threshold = 1
BLAT_pp_mem_threshold = 2
DIAMOND_pp_mem_threshold = 2
DETECT_mem_threshold = 2
Infernal_mem_threshold = 2
Barrnap_mem_threshold = 2

#maximum allowable concurrent instances of the tool [1-number of cores on your machine]
BWA_job_limit = 4
BLAT_job_limit = 4
DIAMOND_job_limit = 4
BWA_pp_job_limit = 4
BLAT_pp_job_limit = 4
DIAMOND_pp_job_limit = 4
DETECT_job_limit = 4
Infernal_job_limit = 4
Barrnap_job_limit = 4
TA_job_limit = 1

#determines how long (seconds) each job should wait before they are launched (imposes delay.  for memory-use-detection)
BWA_job_delay = 5
BLAT_job_delay = 5
DIAMOND_job_delay = 5
BWA_pp_job_delay = 5
BLAT_pp_job_delay = 5
DIAMOND_pp_job_delay = 5

#toggle these options to delete the interim data the steps will generate
keep_all = yes
keep_quality = no
keep_host = no
keep_vector = no
keep_rRNA = no
keep_repop = no
keep_assemble_contigs = yes
keep_GA_BWA = no
keep_GA_BLAT = no
keep_GA_DIAMOND = no
keep_GA_final = no
keep_TA = no
keep_EC = no
keep_outputs = no

#Data gets chunked in the pipeline.  Control the chunk size to reduece the number of files generated.  Increase for speed, and reduced memory load per tool-run [1-99999]
rRNA_chunk_size = 50000
GA_chunk_size = 10000
EC_chunk_size = 1000

#Decides the lossiness of host + vector filtration.  For paired-end annotation only.  [high/low] high: only if both pairs pass through the filter.  low: if either pair passes through filter, both pairs pass
filter_stringency = high


TA_mem_threshold = 5
TA_job_delay = 600


[Labels]
GA_pre_scan = order_1_GA_pre_scan
GA_BWA = order_test_GA_BWA_1
GA_BLAT = order_test_GA_BLAT_1
host_filter = host_read_filter
vector_filter = vector_read_filter
ta = order_ta_1
GA_DIAMOND = order_test_GA_dmd_1
